version: '3.9'
services:
  web:
    image: php:8.2-apache
    container_name: apache
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db
  db:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: casaos
      MYSQL_DATABASE: casaos
      MYSQL_USER: casaos
      MYSQL_PASSWORD: casaos
      PGID: $PGID
      PUID:	$PUID
      REMOTE_SQL:	Value
      TZ:	$TZ
    volumes:
      - ./DATA/AppData/mariadb/config
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8090:8090"
    depends_on:
      - db




